name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: dump info
        run: |
          echo ${{ steps.deployment.outputs.page_url }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
        
      - name: build
        run: |
          npm i
          npm run build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
